acc:
  id: producer000
  seckey: 1rANSfcRzr4HkhbUFZ7L1Zp69JZZHiDDq5v7dNSbbEqeU4jxy3fszV4HGiaLQEyqVpS1dKT9g7zCVRxBVzuiUzB
  algorithm: ed25519
genesis: /var/lib/iserver/genesis
vm:
  jspath: vm/v8vm/v8/libjs/
  loglevel: ""
  maxTxLimitTime: 200
db:
  ldbpath: /var/lib/iserver/storage/
snapshot:
  enable: false
  filepath: /var/lib/iserver/storage/snapshot.tar.gz
p2p:
  listenaddr: 0.0.0.0:30000
  seednodes:
  chainid: 1020
  version: 1
  datapath: /var/lib/iserver/p2p/
  inboundConn: 20
  outboundConn: 10
  blackPID:
  blackIP:
  adminPort: 30005
rpc:
  enable: true
  gatewayaddr: 0.0.0.0:30001
  grpcaddr: 0.0.0.0:30002
  trytx: false
  exectx: false
  allowOrigins:
    - "*"
log:
  filelog:
    path: /var/lib/iserver/logs/
    level: info
    enable: true
  consolelog:
    level: info
    enable: true
  asyncwrite: true
  enablecontractlog: true
metrics:
  pushaddr:
  username:
  password:
  enable: false
  id: iost-testnet:visitor00
debug:
  listenaddr: 0.0.0.0:30003
version:
  netname: "debugnet"
  protocolversion: "1.0"
