name: go-iost GitHub CI
# on: [push]
#on: workflow_dispatch

 on:
   push:
     branches: [ main ]

jobs:
  Mac_Test:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - run: |
        go mod vendor
        HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.0
        git lfs pull
        make vmlib_install
        make build
        PATH=$HOME/bin:$PATH make lint
        make test

  Docker_Test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - run: |
        go mod vendor
        docker pull iostio/iost-dev:3.7.1
        echo ${{ secrets.DOCKERHUBPWD }} | docker login --username ${{ secrets.DOCKERHUBID }}  --password-stdin
        git lfs pull
        make docker_build
        make docker_lint
        make docker_test
  
  E2E_Test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: |
        go mod vendor
        docker pull iostio/iost-dev:3.7.1
        echo ${{ secrets.DOCKERHUBPWD }} | docker login --username ${{ secrets.DOCKERHUBID }}  --password-stdin
        git lfs pull
        make e2e_test

  LinuxTest:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - run: |
        go mod vendor
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.37.0
        git lfs pull
        make vmlib_install
        make build
        PATH=$(HOME)/bin:$PATH make lint
        make test